export const SEARCH = {
  START_SEARCH: 'START_SEARCH',
  SUCCESS_SEARCH: 'SUCCESS_SEARCH',
  FAIL_SEARCH: 'FAIL_SEARCH'
};

export const PLAY = {
  SET_IFRAME: 'SET_IFRAME',
  PLAY: 'PLAY',
  PAUSE: 'PAUSE',
  CUE: 'CUE',
  CHECK_ITEM: 'CHECK_ITEM',
  UNCHECK_ITEM: 'UNCHECK_ITEM',
  END: 'END',
  CLOSE_VIEW: 'CLOSE_VIEW',
  OPEN_VIEW: 'OPEN_VIEW',
  REMOVE: 'REMOVE',
  SHUFFLE: 'SHUFFLE',
  LOOP: 'LOOP',
  SELECT_PLAYLIST: 'SELECT_PLAYLIST'
}

export const PLAYLIST = {
  SAVE: 'SAVE',
  FETCH: 'FETCH',
  SELECT: 'SELECT'
}
