export const SEARCH = {
  START_SEARCH: 'START_SEARCH',
  SUCCESS_SEARCH: 'SUCCESS_SEARCH',
  FAIL_SEARCH: 'FAIL_SEARCH'
};

export const PLAY = {
  PLAY: 'PLAY',
  CUE: 'CUE',
  CHECK_ITEM: 'CHECK_ITEM',
  UNCHECK_ITEM: 'UNCHECK_ITEM'
}
